/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author Américo Ever
 */
public class tela_diciplinas extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public tela_diciplinas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_prog = new javax.swing.JButton();
        btn_sd = new javax.swing.JButton();
        btn_pw = new javax.swing.JButton();
        btn_bd = new javax.swing.JButton();
        btn_ed = new javax.swing.JButton();
        btn_micro = new javax.swing.JButton();
        btn_voltar_disciplinas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Disciplinas");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(420, 380, 160, 32);

        btn_prog.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_prog.setForeground(new java.awt.Color(0, 102, 102));
        btn_prog.setText("Programacao");
        btn_prog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_progActionPerformed(evt);
            }
        });
        jPanel1.add(btn_prog);
        btn_prog.setBounds(160, 440, 290, 40);

        btn_sd.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_sd.setForeground(new java.awt.Color(0, 102, 102));
        btn_sd.setText("Sistemas distribuidos");
        btn_sd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sdActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sd);
        btn_sd.setBounds(530, 439, 298, 40);

        btn_pw.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_pw.setForeground(new java.awt.Color(0, 102, 102));
        btn_pw.setText("Programacao web");
        btn_pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pwActionPerformed(evt);
            }
        });
        jPanel1.add(btn_pw);
        btn_pw.setBounds(160, 509, 290, 40);

        btn_bd.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_bd.setForeground(new java.awt.Color(0, 102, 102));
        btn_bd.setText("Base de dados");
        btn_bd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bdActionPerformed(evt);
            }
        });
        jPanel1.add(btn_bd);
        btn_bd.setBounds(530, 509, 298, 40);

        btn_ed.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_ed.setForeground(new java.awt.Color(0, 102, 102));
        btn_ed.setText("Eletronica Digital");
        btn_ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ed);
        btn_ed.setBounds(160, 580, 290, 40);

        btn_micro.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_micro.setForeground(new java.awt.Color(0, 102, 102));
        btn_micro.setText("Micro Processadores e comp.Pessoais");
        btn_micro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_microActionPerformed(evt);
            }
        });
        jPanel1.add(btn_micro);
        btn_micro.setBounds(530, 580, 298, 50);

        btn_voltar_disciplinas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_voltar_disciplinas.setForeground(new java.awt.Color(0, 102, 102));
        btn_voltar_disciplinas.setText("Voltar");
        btn_voltar_disciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltar_disciplinasActionPerformed(evt);
            }
        });
        jPanel1.add(btn_voltar_disciplinas);
        btn_voltar_disciplinas.setBounds(781, 720, 140, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tudo .png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1000, 1060);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltar_disciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltar_disciplinasActionPerformed
        // TODO add your handling code here:
        tela_login objtela_login = new tela_login();
        objtela_login.setVisible(true);
        dispose();


    }//GEN-LAST:event_btn_voltar_disciplinasActionPerformed

    private void btn_progActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_progActionPerformed
        // TODO add your handling code here:
        tela_conteudoProg objtela_conteudo1 = new tela_conteudoProg();
        objtela_conteudo1.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_progActionPerformed

    private void btn_sdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sdActionPerformed
        // TODO add your handling code here:
        tela_conteudoSD objtela_conteudoSD = new tela_conteudoSD();
        objtela_conteudoSD.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_sdActionPerformed

    private void btn_pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pwActionPerformed
        // TODO add your handling code here:
        tela_conteudoPW objtela_conteudoPW = new tela_conteudoPW();
        objtela_conteudoPW.setVisible(true);

        dispose();
    }//GEN-LAST:event_btn_pwActionPerformed

    private void btn_bdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bdActionPerformed
        // TODO add your handling code here:
        tela_conteudoBD objtela_conteudoBD = new tela_conteudoBD();
        objtela_conteudoBD.setVisible(true);

        dispose();
    }//GEN-LAST:event_btn_bdActionPerformed

    private void btn_edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edActionPerformed
        // TODO add your handling code here:
        tela_conteudoED objtela_conteudoED = new tela_conteudoED();
        objtela_conteudoED.setVisible(true);

        dispose();
    }//GEN-LAST:event_btn_edActionPerformed

    private void btn_microActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_microActionPerformed
        // TODO add your handling code here:
        tela_conteudoMicro objtela_conteudoMicro = new tela_conteudoMicro();
        objtela_conteudoMicro.setVisible(true);

        dispose();
    }//GEN-LAST:event_btn_microActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_diciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_diciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_diciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_diciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_diciplinas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bd;
    private javax.swing.JButton btn_ed;
    private javax.swing.JButton btn_micro;
    private javax.swing.JButton btn_prog;
    private javax.swing.JButton btn_pw;
    private javax.swing.JButton btn_sd;
    private javax.swing.JButton btn_voltar_disciplinas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
