/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import DAO.cadastroDAO;
import Getset.cadastroDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author Américo Ever
 */
public class tela_cadastro extends javax.swing.JFrame {

    /**
     * Creates new form tela_cadastro
     */
    public tela_cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_cadastrar = new javax.swing.JButton();
        btn_cancelar_cadastro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_nome_cadastrar = new javax.swing.JTextField();
        txt_apelido_cadastrar = new javax.swing.JTextField();
        txt_email_cadastrar = new javax.swing.JTextField();
        txt_senha_cadastrar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        btn_cadastrar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn_cadastrar.setForeground(new java.awt.Color(0, 102, 102));
        btn_cadastrar.setText("Cadastrar-se");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cadastrar);
        btn_cadastrar.setBounds(760, 433, 150, 50);

        btn_cancelar_cadastro.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn_cancelar_cadastro.setForeground(new java.awt.Color(0, 102, 102));
        btn_cancelar_cadastro.setText("Cancelar");
        btn_cancelar_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar_cadastroActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancelar_cadastro);
        btn_cancelar_cadastro.setBounds(760, 510, 150, 50);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Nome");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 240, 67, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Apelido");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 320, 90, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("E-mail");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 400, 80, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Senha");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 480, 60, 50);

        txt_nome_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nome_cadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nome_cadastrar);
        txt_nome_cadastrar.setBounds(50, 280, 608, 40);
        jPanel1.add(txt_apelido_cadastrar);
        txt_apelido_cadastrar.setBounds(50, 360, 608, 40);
        jPanel1.add(txt_email_cadastrar);
        txt_email_cadastrar.setBounds(50, 440, 608, 40);
        jPanel1.add(txt_senha_cadastrar);
        txt_senha_cadastrar.setBounds(50, 530, 608, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tudo .png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 980, 1060);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 979, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nome_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nome_cadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nome_cadastrarActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        // TODO add your handling code here:
        tratamento();
       
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_cancelar_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar_cadastroActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_cancelar_cadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_cancelar_cadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_apelido_cadastrar;
    private javax.swing.JTextField txt_email_cadastrar;
    private javax.swing.JTextField txt_nome_cadastrar;
    private javax.swing.JTextField txt_senha_cadastrar;
    // End of variables declaration//GEN-END:variables
 private void tratamento(){
        if (txt_apelido_cadastrar.getText().isEmpty() || txt_email_cadastrar.getText().isEmpty() || txt_nome_cadastrar.getText().isEmpty()||txt_senha_cadastrar.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Insira dados em todos campos para que possa fazer o cadastro ");
        }else if(txt_email_cadastrar.getText().contains("@")){
            
        String nome, apelido,email,senha;
        
        nome=txt_nome_cadastrar.getText();
        apelido= txt_apelido_cadastrar.getText();
        email=txt_email_cadastrar.getText();
        senha=txt_senha_cadastrar.getText();
        
        cadastroDTO objcadastroDTO = new cadastroDTO();
        objcadastroDTO.setNome_cadastro(nome);
        objcadastroDTO.setApelido_cadastro(apelido);
        objcadastroDTO.setEmail_cadastro(email);
        objcadastroDTO.setSenha_cadastro(senha);
        
        cadastroDAO objcadastroDAO = new cadastroDAO();
        objcadastroDAO.novocadastro(objcadastroDTO);
        
        tela_login objtela_login= new tela_login();
        objtela_login.setVisible(true);
        
        dispose();
        } else{
            
            JOptionPane.showMessageDialog(null, "o email tem de conter " +"@" + " para que seja valido ");
        }
    }
}
