/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import DAO.Conexao;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Américo Ever
 */
public class tela_conteudoBD extends javax.swing.JFrame {

    /**
     * Creates new form tela_conteudoBD
     */
    public tela_conteudoBD() {
        initComponents();
        PopularCBX();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jcb_ids = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btn_SaveLesson = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        btn_back.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btn_back.setForeground(new java.awt.Color(0, 102, 102));
        btn_back.setText("Voltar");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back);
        btn_back.setBounds(1083, 650, 130, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Base de dados Aulas");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(43, 43, 250, 60);

        jcb_ids.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jcb_ids.setForeground(new java.awt.Color(0, 102, 102));
        jcb_ids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_idsActionPerformed(evt);
            }
        });
        jPanel1.add(jcb_ids);
        jcb_ids.setBounds(40, 100, 460, 28);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Conteudo da Aula");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1060, 70, 170, 25);

        btn_SaveLesson.setBackground(new java.awt.Color(0, 102, 102));
        btn_SaveLesson.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btn_SaveLesson.setForeground(new java.awt.Color(255, 255, 255));
        btn_SaveLesson.setText("Salvar Aula");
        btn_SaveLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveLessonActionPerformed(evt);
            }
        });
        jPanel1.add(btn_SaveLesson);
        btn_SaveLesson.setBounds(1060, 110, 150, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/giphy.gif"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(380, 200, 460, 340);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Salve a aula com o mesmo nome e extensao que for visualizado na caixa de seleção");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(260, 550, 790, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo todo.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 1280, 930);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SaveLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveLessonActionPerformed
        // TODO add your handling code here:

        Connection conn;
        PreparedStatement pstm;
        ResultSet rs;

        try {
            conn = new Conexao().connectBD();
            String sql = "select conteudo_bd from bd where tema_bd=?";
            pstm = conn.prepareStatement(sql);

            ///// definindo o valor do parametro para o id do registro
            pstm.setString(1, (String) jcb_ids.getSelectedItem());
            rs = pstm.executeQuery();

            if (rs.next()) {
                Blob blob = rs.getBlob("conteudo_bd");
                //new
                InputStream inputStream = blob.getBinaryStream();

                // abrindo o dialogo de selecao do arquivo
                JFileChooser escolher = new JFileChooser();
                int userSelection = escolher.showSaveDialog(null);

                if (userSelection == JFileChooser.APPROVE_OPTION) {
                    File ficheiroSalvar = escolher.getSelectedFile();

                    //salva o conteudo do blob em um arquivo
                    salavarBlob(inputStream, ficheiroSalvar);
                    JOptionPane.showMessageDialog(null, "arquivo salvo com sucesso");
                }
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "ocorreu um erro ao salvar o arquivo" + erro);
        }

    }//GEN-LAST:event_btn_SaveLessonActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        tela_diciplinas objtela_diciplinas = new tela_diciplinas();
        objtela_diciplinas.setVisible(true);

        dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void jcb_idsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_idsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_idsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_conteudoBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_conteudoBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_conteudoBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_conteudoBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_conteudoBD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_SaveLesson;
    private javax.swing.JButton btn_back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcb_ids;
    // End of variables declaration//GEN-END:variables
public static void salavarBlob(InputStream inputStream, File file) {
        try (FileOutputStream outputStream = new FileOutputStream(file)) {
            byte[] buffer = new byte[4096];
            int bytesRead;

            while ((bytesRead = inputStream.read(buffer)) != -1) {
                outputStream.write(buffer, 0, bytesRead);
            }
        } catch (IOException erro) {
            JOptionPane.showMessageDialog(null, "erro ao salvar blob" + erro);
        }
    }

    private void PopularCBX() {
        Connection conn;
        PreparedStatement pstm;
        ResultSet rs;

        try {
            conn = new Conexao().connectBD();
            Statement statement = conn.createStatement();

            String sql = "select tema_bd from bd";
            rs = statement.executeQuery(sql);

            //adicionar dados a combobox
            while (rs.next()) {
                String tema = rs.getString("tema_bd");
                jcb_ids.addItem(tema);
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "errooooo" + erro);
        }
    }
}
