/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author Américo Ever
 */
public class tela_menu_adimin extends javax.swing.JFrame {

    /**
     * Creates new form tela_menu_adimin
     */
    public tela_menu_adimin() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_ver_estudantes = new javax.swing.JButton();
        btn_inserir_aula = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        btn_actualizar_aula = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu de administracao");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(330, 400, 270, 32);

        btn_ver_estudantes.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_ver_estudantes.setForeground(new java.awt.Color(0, 102, 102));
        btn_ver_estudantes.setText("Modificar as listas de estudantes");
        btn_ver_estudantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ver_estudantesActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ver_estudantes);
        btn_ver_estudantes.setBounds(130, 470, 320, 40);

        btn_inserir_aula.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_inserir_aula.setForeground(new java.awt.Color(0, 102, 102));
        btn_inserir_aula.setText("Inserir aulas ");
        btn_inserir_aula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inserir_aulaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_inserir_aula);
        btn_inserir_aula.setBounds(490, 470, 310, 40);

        btn_back.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_back.setForeground(new java.awt.Color(0, 102, 102));
        btn_back.setText("Sair");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back);
        btn_back.setBounds(759, 679, 140, 40);

        btn_actualizar_aula.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_actualizar_aula.setForeground(new java.awt.Color(0, 102, 102));
        btn_actualizar_aula.setText("Modificar e inserir novas Aulas");
        btn_actualizar_aula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizar_aulaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_actualizar_aula);
        btn_actualizar_aula.setBounds(130, 549, 320, 40);

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Cadastrar Administrador");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(490, 550, 310, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tudo .png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 980, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 973, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inserir_aulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inserir_aulaActionPerformed
        // TODO add your handling code here:
         tela_diciplinas_adm objtela_diciplinas_adm = new tela_diciplinas_adm();
        objtela_diciplinas_adm.setVisible(true);

        dispose();
    }//GEN-LAST:event_btn_inserir_aulaActionPerformed

    private void btn_ver_estudantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ver_estudantesActionPerformed
        // TODO add your handling code here:
        tela_pesquisar_adimin objtela_pesquisar = new tela_pesquisar_adimin();
        objtela_pesquisar.setVisible(true);

        dispose();
    }//GEN-LAST:event_btn_ver_estudantesActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        tela_login objtela_login = new tela_login();
        objtela_login.setVisible(true);
        
        dispose();

    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_actualizar_aulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizar_aulaActionPerformed
        // TODO add your handling code here:
        tela_pesq_aulas objtela_pesq_aulas_aula = new tela_pesq_aulas();
        objtela_pesq_aulas_aula.setVisible(true);

        dispose();
    }//GEN-LAST:event_btn_actualizar_aulaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tela_cadastrar_adm objtela_cadastrar_adm = new tela_cadastrar_adm();
        objtela_cadastrar_adm.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_menu_adimin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_menu_adimin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_menu_adimin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_menu_adimin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_menu_adimin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar_aula;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_inserir_aula;
    private javax.swing.JButton btn_ver_estudantes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
