/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import DAO.Cadastro_admDAO;
import Getset.Cadastro_admDTO;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Américo Ever
 */
public class tela_cadastrar_adm extends javax.swing.JFrame {

    /**
     * Creates new form tela_actualizar_aula
     */
    public tela_cadastrar_adm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_apelido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_bi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_nuit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_morrada = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_senha = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btn_cadastro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Nome");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 270, 80, 30);
        jPanel2.add(txt_nome);
        txt_nome.setBounds(40, 310, 670, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Apelido");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 350, 80, 30);
        jPanel2.add(txt_apelido);
        txt_apelido.setBounds(40, 380, 670, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("BI");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(40, 420, 50, 25);
        jPanel2.add(txt_bi);
        txt_bi.setBounds(40, 450, 670, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NUIT");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(40, 500, 90, 25);
        jPanel2.add(txt_nuit);
        txt_nuit.setBounds(40, 536, 670, 40);

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Morrada");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(40, 590, 90, 30);
        jPanel2.add(txt_morrada);
        txt_morrada.setBounds(40, 630, 670, 40);

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Senha");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(40, 680, 80, 25);
        jPanel2.add(txt_senha);
        txt_senha.setBounds(40, 720, 670, 40);

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(800, 710, 130, 40);

        btn_cadastro.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_cadastro.setForeground(new java.awt.Color(0, 102, 102));
        btn_cadastro.setText("Cadastrar");
        btn_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastroActionPerformed(evt);
            }
        });
        jPanel2.add(btn_cadastro);
        btn_cadastro.setBounds(800, 630, 130, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tudo .png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 1003, 1060);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1003, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastroActionPerformed
        // TODO add your handling code here:
        tratamento();

        
    }//GEN-LAST:event_btn_cadastroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tela_menu_adimin objtela_menu_adimin = new tela_menu_adimin();
        objtela_menu_adimin.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_cadastrar_adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_cadastrar_adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_cadastrar_adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_cadastrar_adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_cadastrar_adm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_apelido;
    private javax.swing.JTextField txt_bi;
    private javax.swing.JTextField txt_morrada;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_nuit;
    private javax.swing.JTextField txt_senha;
    // End of variables declaration//GEN-END:variables
  private void tratamento(){
        if (txt_apelido.getText().isEmpty() || txt_bi.getText().isEmpty() || txt_morrada.getText().isEmpty()||txt_nome.getText().isEmpty()
                || txt_nuit.getText().isEmpty()|| txt_senha.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Insira dados em todos campos para que possa fazer o cadastro ");
        }else{
            String nome_admin;
        String apelido_admin;
        String bi_admin;
        String morrada_admin;
        String senha_admin;
        int id_admin;
        int nuit_admin;

        nome_admin = txt_nome.getText();
        apelido_admin = txt_apelido.getText();
        bi_admin = txt_bi.getText();
        morrada_admin = txt_morrada.getText();
        senha_admin = txt_senha.getText();
        nuit_admin = Integer.parseInt(txt_nuit.getText());
        

        Cadastro_admDTO objcadastro_admDTO = new Cadastro_admDTO();
        objcadastro_admDTO.setNome_admin(nome_admin);
        objcadastro_admDTO.setApelido_admin(apelido_admin);
        objcadastro_admDTO.setBi_admin(bi_admin);
        objcadastro_admDTO.setNuit_admin(nuit_admin);
        objcadastro_admDTO.setMorrada_admin(morrada_admin);
        objcadastro_admDTO.setSenha_admin(senha_admin);

        Cadastro_admDAO objcadastroadmDAO = new Cadastro_admDAO();
        objcadastroadmDAO.adminCadastro(objcadastro_admDTO);

        tela_login objtela_login = new tela_login();
        objtela_login.setVisible(true);

        dispose();
        }
    }
}
