/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import DAO.Conexao;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Américo Ever
 */
public class tela_inserir_aulaProg extends javax.swing.JFrame {

    /**
     * Creates new form tela_inserir_aula
     */
    public tela_inserir_aulaProg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sssss = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_select_aula = new javax.swing.JButton();
        btn_limpar = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        txt_caminho = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_submeter_aula = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_tema_aula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        sssss.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Aulas De Programacao");
        sssss.add(jLabel1);
        jLabel1.setBounds(370, 410, 250, 32);

        btn_select_aula.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_select_aula.setForeground(new java.awt.Color(0, 102, 102));
        btn_select_aula.setText("Escolher a Aula");
        btn_select_aula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_select_aulaActionPerformed(evt);
            }
        });
        sssss.add(btn_select_aula);
        btn_select_aula.setBounds(70, 469, 170, 40);

        btn_limpar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_limpar.setForeground(new java.awt.Color(0, 102, 102));
        btn_limpar.setText("Limpar Campo");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });
        sssss.add(btn_limpar);
        btn_limpar.setBounds(750, 589, 170, 40);

        btn_back.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_back.setForeground(new java.awt.Color(0, 102, 102));
        btn_back.setText("Sair");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        sssss.add(btn_back);
        btn_back.setBounds(750, 740, 170, 40);
        sssss.add(txt_caminho);
        txt_caminho.setBounds(70, 546, 621, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Caminho do Arquivo");
        sssss.add(jLabel2);
        jLabel2.setBounds(70, 520, 190, 20);

        btn_submeter_aula.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_submeter_aula.setForeground(new java.awt.Color(0, 102, 102));
        btn_submeter_aula.setText("Submeter Aula");
        btn_submeter_aula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submeter_aulaActionPerformed(evt);
            }
        });
        sssss.add(btn_submeter_aula);
        btn_submeter_aula.setBounds(750, 509, 170, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tema da aula");
        sssss.add(jLabel3);
        jLabel3.setBounds(70, 600, 160, 25);
        sssss.add(txt_tema_aula);
        txt_tema_aula.setBounds(70, 636, 621, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tudo .png"))); // NOI18N
        sssss.add(jLabel4);
        jLabel4.setBounds(0, 0, 1000, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sssss, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sssss, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_select_aulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_select_aulaActionPerformed
        // TODO add your handling code here:
        JFileChooser escolher = new JFileChooser();
        escolher.setDialogTitle("Procurar aquivo");
        escolher.setFileSelectionMode(JFileChooser.FILES_ONLY);

        FileNameExtensionFilter filter = new FileNameExtensionFilter("ficheiros", "pdf", "txt", "jpg", "png");

        escolher.setFileFilter(filter);
        int retorno = escolher.showOpenDialog(this);

        if (retorno == JFileChooser.APPROVE_OPTION) {
            File file = escolher.getSelectedFile();
            txt_caminho.setText(file.getPath());

        }
    }//GEN-LAST:event_btn_select_aulaActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        tela_diciplinas_adm objtela_diciplinas_adm = new tela_diciplinas_adm();
        objtela_diciplinas_adm.setVisible(true);

        dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        // TODO add your handling code here:
        LimparCampos();


    }//GEN-LAST:event_btn_limparActionPerformed

    private void btn_submeter_aulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submeter_aulaActionPerformed

        Connection conn;
        PreparedStatement pstm;

        if (txt_caminho.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o directorio ou selecione um ficheiro");

        } else if (txt_tema_aula.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo com o titulo da aula");
        } else if (txt_tema_aula.getText().contains(".txt") || txt_tema_aula.getText().contains(".pdf")
                || txt_tema_aula.getText().contains(".jpg") || txt_tema_aula.getText().contains(".png")) {
            try {
                conn = new Conexao().connectBD();
                String tema_prog = txt_tema_aula.getText();
                String Caminho = txt_caminho.getText();
                File file = new File(Caminho);
                FileInputStream fis = new FileInputStream(file);

                byte[] fileData = new byte[(int) file.length()];
                fis.read(fileData);
                fis.close();

                String sql = "insert into programacao (tema_prog,conteudo_prog) values (?,?) ";
                pstm = conn.prepareStatement(sql);
                pstm.setString(1, tema_prog);
                pstm.setBytes(2, fileData);
                pstm.executeUpdate();
                pstm.close();

            } catch (Exception erro) {
                JOptionPane.showMessageDialog(null, "Erro ao submeter aula" + erro);
            }
            JOptionPane.showMessageDialog(null, "Arquivo submetido com sucesso");
        } else {
            JOptionPane.showMessageDialog(null, "adicione a extensao do arquivo ao tema da aula para poder submeter");

        }
//         try {
//            ArquivoController arquivoController = new ArquivoController();
//            arquivoController.lerArquivo(Caminho);
//            byte[] arrayDeBytes = arquivoController.getArrayDeBytes();
//            tela_conteudo1 objtela_conteudo1 =  new tela_conteudo1(arrayDeBytes);
//        } catch (Exception erro) {
//            erro.printStackTrace();
//        }
//        
//        try {
//            String Caminho = txt_caminho.getText();
//            JOptionPane.showMessageDialog(null,"Arquivo Lido com sucesso");
//        } catch (Exception erro) {
//            erro.printStackTrace();
//             JOptionPane.showMessageDialog(null,"erro ao ler arquivo" + erro.getMessage());
//            
//        }}
//        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        setContentPane(contentPane);
//        pack();
//        setLocationRelativeTo(null);
//        setVisible(true);
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(tela_inserir_aula.class.getName()).log(Level.SEVERE, null, ex);
//        } finally {
//            try {
//                fis.close();
//            } catch (IOException ex) {
//                Logger.getLogger(tela_inserir_aula.class.getName()).log(Level.SEVERE, null, ex);
//            }


    }//GEN-LAST:event_btn_submeter_aulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_inserir_aulaProg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_inserir_aulaProg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_inserir_aulaProg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_inserir_aulaProg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_inserir_aulaProg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JButton btn_select_aula;
    private javax.swing.JButton btn_submeter_aula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel sssss;
    private javax.swing.JTextField txt_caminho;
    private javax.swing.JTextField txt_tema_aula;
    // End of variables declaration//GEN-END:variables
 private void LimparCampos() {
        txt_tema_aula.setText("");
        txt_caminho.setText("");
    }

}
