/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author Américo Ever
 */
public class tela_diciplinas_adm extends javax.swing.JFrame {

    /**
     * Creates new form tela_diciplinas_adm
     */
    public tela_diciplinas_adm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_insertProgramacao = new javax.swing.JButton();
        btn_insertPW = new javax.swing.JButton();
        btn_insertED = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        btn_insertSD = new javax.swing.JButton();
        btn_insertBD = new javax.swing.JButton();
        btn_insertMicro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Diciplinas");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(420, 410, 190, 32);

        btn_insertProgramacao.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_insertProgramacao.setForeground(new java.awt.Color(0, 102, 102));
        btn_insertProgramacao.setText("Programacao");
        btn_insertProgramacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertProgramacaoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_insertProgramacao);
        btn_insertProgramacao.setBounds(200, 490, 270, 40);

        btn_insertPW.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_insertPW.setForeground(new java.awt.Color(0, 102, 102));
        btn_insertPW.setText("Programacao web");
        btn_insertPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertPWActionPerformed(evt);
            }
        });
        jPanel1.add(btn_insertPW);
        btn_insertPW.setBounds(200, 560, 270, 40);

        btn_insertED.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_insertED.setForeground(new java.awt.Color(0, 102, 102));
        btn_insertED.setText("Eletronica Digital");
        btn_insertED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertEDActionPerformed(evt);
            }
        });
        jPanel1.add(btn_insertED);
        btn_insertED.setBounds(200, 640, 270, 40);

        btn_back.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_back.setForeground(new java.awt.Color(0, 102, 102));
        btn_back.setText("Voltar");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back);
        btn_back.setBounds(795, 780, 130, 40);

        btn_insertSD.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_insertSD.setForeground(new java.awt.Color(0, 102, 102));
        btn_insertSD.setText("Sistemas distribuidos");
        btn_insertSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertSDActionPerformed(evt);
            }
        });
        jPanel1.add(btn_insertSD);
        btn_insertSD.setBounds(520, 489, 290, 40);

        btn_insertBD.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_insertBD.setForeground(new java.awt.Color(0, 102, 102));
        btn_insertBD.setText("Base de dados");
        btn_insertBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertBDActionPerformed(evt);
            }
        });
        jPanel1.add(btn_insertBD);
        btn_insertBD.setBounds(523, 559, 290, 40);

        btn_insertMicro.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_insertMicro.setForeground(new java.awt.Color(0, 102, 102));
        btn_insertMicro.setText("Micro Processadores e comp.Pessoais");
        btn_insertMicro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertMicroActionPerformed(evt);
            }
        });
        jPanel1.add(btn_insertMicro);
        btn_insertMicro.setBounds(520, 639, 300, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tudo .png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1003, 1110);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_insertProgramacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertProgramacaoActionPerformed
        // TODO add your handling code here:
        tela_inserir_aulaProg objtela_inserir_aulaProg = new tela_inserir_aulaProg();
        objtela_inserir_aulaProg.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_insertProgramacaoActionPerformed

    private void btn_insertMicroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertMicroActionPerformed
        // TODO add your handling code here:
        tela_inserir_aulaMicro objtela_inserir_aulaMicro = new tela_inserir_aulaMicro();
        objtela_inserir_aulaMicro.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_insertMicroActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        tela_menu_adimin objtela_menu_adimin = new tela_menu_adimin();
        objtela_menu_adimin.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_insertSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertSDActionPerformed
        // TODO add your handling code here:
        tela_inserir_aulaSD objtela_inserir_aulaSD = new tela_inserir_aulaSD();
        objtela_inserir_aulaSD.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_insertSDActionPerformed

    private void btn_insertPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertPWActionPerformed
        // TODO add your handling code here:
         tela_inserir_aulaPW objtela_inserir_aulaPW = new tela_inserir_aulaPW();
        objtela_inserir_aulaPW.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_insertPWActionPerformed

    private void btn_insertBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertBDActionPerformed
        // TODO add your handling code here:
         tela_inserir_aulaBD objtela_inserir_aulaBD = new tela_inserir_aulaBD();
        objtela_inserir_aulaBD.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_insertBDActionPerformed

    private void btn_insertEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertEDActionPerformed
        // TODO add your handling code here:
         tela_inserir_aulaED objtela_inserir_aulaED = new tela_inserir_aulaED();
        objtela_inserir_aulaED.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_insertEDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_diciplinas_adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_diciplinas_adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_diciplinas_adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_diciplinas_adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_diciplinas_adm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_insertBD;
    private javax.swing.JButton btn_insertED;
    private javax.swing.JButton btn_insertMicro;
    private javax.swing.JButton btn_insertPW;
    private javax.swing.JButton btn_insertProgramacao;
    private javax.swing.JButton btn_insertSD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
